# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CollectionApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionApp
  pod 'SDWebImage', '~> 5.0'

  target 'CollectionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CollectionAppUITests' do
    # Pods for testing
  end

end
